name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Verify Node.js version
      run: |
        node --version
        npm --version
        which node
        which npm
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Capacitor CLI globally
      run: npm install -g @capacitor/cli@latest
    
    - name: Build web app
      run: npm run build
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '34'
        sdk-build-tools: '34.0.0'
    
    - name: Sync Capacitor
      run: |
        node --version
        cap --version
        cap sync
      env:
        PATH: ${{ env.PATH }}
    
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: biomap-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk 