name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web app
      run: npm run build
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Android SDK
      run: |
        mkdir -p $ANDROID_HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q commandlinetools-linux-11076708_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
    
    - name: Sync Capacitor
      run: npx cap sync
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:$PATH
    
    - name: Configure Java version for all modules
      run: |
        cd android
        echo "Setting Java version for all modules..."
        find . -name "build.gradle" -exec sed -i 's/sourceCompatibility JavaVersion.VERSION_21/sourceCompatibility JavaVersion.VERSION_17/g' {} \;
        find . -name "build.gradle" -exec sed -i 's/targetCompatibility JavaVersion.VERSION_21/targetCompatibility JavaVersion.VERSION_17/g' {} \;
        find . -name "build.gradle" -exec sed -i 's/sourceCompatibility = JavaVersion.VERSION_21/sourceCompatibility = JavaVersion.VERSION_17/g' {} \;
        find . -name "build.gradle" -exec sed -i 's/targetCompatibility = JavaVersion.VERSION_21/targetCompatibility = JavaVersion.VERSION_17/g' {} \;
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:$PATH
    
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug --info
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:$PATH
        JAVA_HOME: ${{ env.JAVA_HOME }}
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: biomap-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk 